<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$c=load_config();$has=!empty($c['admin_password_hash']);$error='';$success='';
if(isset($_GET['logout'])){unset($_SESSION['alipay_admin']);header('Location: settings.php');exit;}
if($has&&empty($_SESSION['alipay_admin'])){
 if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['login_password'])){if(password_verify((string)$_POST['login_password'],(string)$c['admin_password_hash'])){$_SESSION['alipay_admin']=true;header('Location: settings.php');exit;}$error='管理密码错误';}
 if(empty($_SESSION['alipay_admin'])){?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>支付宝配置登录</title><link rel="stylesheet" href="assets/app.css"></head><body class="provider-alipay"><div class="login-wrap"><div class="login-card"><div class="login-mark">付</div><h1>支付宝配置</h1><p>请输入管理密码后进入支付参数配置中心。</p><?php if($error):?><div class="alert err"><?=htmlspecialchars($error)?></div><?php endif;?><form method="post"><div class="field"><label>管理密码</label><input class="input" type="password" name="login_password" required autofocus placeholder="请输入管理密码"></div><button class="btn btn-primary btn-block">进入配置</button></form></div></div></body></html><?php exit;}
}
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['save'])){try{if(!$has){$p=(string)($_POST['new_admin_password']??'');if(strlen($p)<6)throw new RuntimeException('首次设置需要至少 6 位管理密码');$c['admin_password_hash']=password_hash($p,PASSWORD_DEFAULT);$_SESSION['alipay_admin']=true;$has=true;}$c['gateway']=trim((string)($_POST['gateway']??''));$c['app_id']=trim((string)($_POST['app_id']??''));$c['alipay_public_key']=trim((string)($_POST['alipay_public_key']??''));$c['notify_url']=trim((string)($_POST['notify_url']??''));$pk=trim((string)($_POST['app_private_key']??''));if($pk!=='')$c['app_private_key']=$pk;if(!preg_match('#^https://#i',$c['gateway']))throw new RuntimeException('支付宝网关必须是 https://');save_config($c);$success='配置已保存';}catch(Throwable $e){$error=$e->getMessage();}}
?>
<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>支付宝支付配置</title><link rel="stylesheet" href="assets/app.css"></head><body class="provider-alipay">
<header class="app-header"><div class="header-inner"><a class="brand" href="./"><div class="brand-mark">付</div><div><div class="brand-title">Payment Lab</div><div class="brand-sub">支付接口联调中心</div></div></a><nav class="top-nav"><a href="./">支付宝测试</a><a href="wechat.php">微信支付</a><a class="active" href="settings.php">支付宝配置</a><a href="wechat-settings.php">微信配置</a></nav></div></header>
<main class="page"><section class="hero"><div><div class="eyebrow">ALIPAY SETTINGS</div><h1>支付宝接口配置</h1><p>密钥仅保存在服务器端，页面不会回显已保存的应用私钥。</p></div><div class="status-pill <?=ready($c)?'':'off'?>"><?=ready($c)?'配置完整':'配置未完成'?></div></section>
<?php if($success):?><div class="alert ok"><?=htmlspecialchars($success)?></div><?php endif;?><?php if($error):?><div class="alert err"><?=htmlspecialchars($error)?></div><?php endif;?>
<form method="post" autocomplete="off"><input type="hidden" name="save" value="1">
<section class="section-card"><div class="section-head"><div><h2>基础参数</h2><div class="card-sub">应用身份与支付宝网关</div></div></div><div class="section-body"><div class="form-grid">
<?php if(!$has):?><div class="form-label">首次管理密码</div><div><input class="input" type="password" name="new_admin_password" minlength="6" required placeholder="至少 6 位"><div class="help">用于以后进入支付配置后台。</div></div><?php endif;?>
<div class="form-label">支付宝网关</div><div><input class="input" name="gateway" value="<?=htmlspecialchars((string)$c['gateway'])?>" required><div class="help">正式环境默认：https://openapi.alipay.com/gateway.do</div></div>
<div class="form-label">APPID</div><div><input class="input" name="app_id" value="<?=htmlspecialchars((string)$c['app_id'])?>" placeholder="支付宝应用 APPID"></div>
</div></div></section>
<section class="section-card"><div class="section-head"><div><h2>签名密钥</h2><div class="card-sub">用于 RSA2 请求签名与异步通知验签</div></div></div><div class="section-body"><div class="form-grid">
<div class="form-label">应用私钥</div><div><textarea class="textarea" name="app_private_key" placeholder="<?=$c['app_private_key']?'已保存；不修改请留空':'粘贴应用私钥'?>"></textarea><div class="help">私钥保存在服务器 <span class="code">storage/config.json</span>，不会重新显示。</div></div>
<div class="form-label">支付宝公钥</div><div><textarea class="textarea" name="alipay_public_key" placeholder="支付宝公钥"><?=htmlspecialchars((string)$c['alipay_public_key'])?></textarea></div>
</div></div></section>
<section class="section-card"><div class="section-head"><div><h2>回调设置</h2><div class="card-sub">支付宝付款完成后的服务器通知地址</div></div></div><div class="section-body"><div class="form-grid"><div class="form-label">异步通知地址</div><div><input class="input" name="notify_url" value="<?=htmlspecialchars((string)$c['notify_url'])?>" placeholder="<?=htmlspecialchars(base_url().'/notify.php')?>"><div class="help">当前使用：<span class="code"><?=htmlspecialchars(notify_url($c))?></span></div></div></div></div></section>
<div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap"><a class="btn btn-soft" href="./">返回支付测试</a><div style="display:flex;gap:10px"><a class="btn btn-soft" href="?logout=1">退出登录</a><button class="btn btn-primary" type="submit">保存支付宝配置</button></div></div>
</form><div class="footer-note">安全提示：不要把真实私钥提交到 GitHub 或展示在前端页面。</div></main></body></html>