<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$c=load_config();$has=!empty($c['admin_password_hash']);$error='';$success='';
if(isset($_GET['logout'])){unset($_SESSION['alipay_admin']);header('Location: settings.php');exit;}
if($has&&empty($_SESSION['alipay_admin'])){
 if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['login_password'])){if(password_verify((string)$_POST['login_password'],(string)$c['admin_password_hash'])){$_SESSION['alipay_admin']=true;header('Location: settings.php');exit;}$error='管理密码错误';}
 if(empty($_SESSION['alipay_admin'])){?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>配置登录</title><style>body{font-family:Arial;background:#f4f7fb}.box{max-width:420px;margin:12vh auto;background:#fff;padding:28px;border-radius:16px;box-shadow:0 10px 35px #0001}input,button{width:100%;box-sizing:border-box;padding:13px;border-radius:9px}input{border:1px solid #ddd}button{border:0;background:#1677ff;color:white;font-weight:700;margin-top:12px}.err{color:#dc2626}</style></head><body><div class="box"><h2>支付宝配置</h2><?php if($error):?><p class="err"><?=htmlspecialchars($error)?></p><?php endif;?><form method="post"><input type="password" name="login_password" required autofocus placeholder="管理密码"><button>登录</button></form></div></body></html><?php exit;}
}
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['save'])){try{if(!$has){$p=(string)($_POST['new_admin_password']??'');if(strlen($p)<6)throw new RuntimeException('首次设置需要至少 6 位管理密码');$c['admin_password_hash']=password_hash($p,PASSWORD_DEFAULT);$_SESSION['alipay_admin']=true;$has=true;}$c['gateway']=trim((string)($_POST['gateway']??''));$c['app_id']=trim((string)($_POST['app_id']??''));$c['alipay_public_key']=trim((string)($_POST['alipay_public_key']??''));$c['notify_url']=trim((string)($_POST['notify_url']??''));$pk=trim((string)($_POST['app_private_key']??''));if($pk!=='')$c['app_private_key']=$pk;if(!preg_match('#^https://#i',$c['gateway']))throw new RuntimeException('支付宝网关必须是 https://');save_config($c);$success='配置已保存';}catch(Throwable $e){$error=$e->getMessage();}}
?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>支付宝配置</title><style>*{box-sizing:border-box}body{margin:0;background:#f4f7fb;font-family:Arial,"Microsoft YaHei";color:#1f2937}.top{background:#1677ff;color:#fff;padding:18px 22px;font-size:21px;font-weight:700}.wrap{max-width:820px;margin:26px auto;padding:0 16px}.card{background:#fff;padding:24px;border-radius:15px;box-shadow:0 7px 28px #0001}label{display:block;font-weight:700;font-size:13px;margin:17px 0 7px}input,textarea{width:100%;border:1px solid #d7deea;border-radius:9px;padding:12px}textarea{min-height:120px}.btn{border:0;background:#1677ff;color:#fff;padding:12px 20px;border-radius:9px;font-weight:700;margin-top:20px}.note{font-size:13px;color:#64748b;line-height:1.7}.ok,.err{padding:12px;border-radius:9px;margin:12px 0}.ok{background:#ecfdf5;color:#047857}.err{background:#fef2f2;color:#b91c1c}a{color:#1677ff;text-decoration:none}.code{word-break:break-all;background:#f8fafc;padding:8px;border-radius:7px}</style></head><body><div class="top">支付宝当面付 · 配置</div><div class="wrap"><div class="card"><p><a href="./">← 返回支付页</a><?php if($has):?> · <a href="?logout=1">退出</a><?php endif;?></p><h2>真实二维码测试配置</h2><p>状态：<b><?=ready($c)?'配置完整':'配置未完成'?></b></p><?php if($success):?><div class="ok"><?=htmlspecialchars($success)?></div><?php endif;?><?php if($error):?><div class="err"><?=htmlspecialchars($error)?></div><?php endif;?><form method="post" autocomplete="off"><input type="hidden" name="save" value="1"><?php if(!$has):?><label>首次设置：管理密码</label><input type="password" name="new_admin_password" minlength="6" required><?php endif;?><label>支付宝网关</label><input name="gateway" value="<?=htmlspecialchars((string)$c['gateway'])?>" required><div class="note">正式环境默认：https://openapi.alipay.com/gateway.do</div><label>APPID</label><input name="app_id" value="<?=htmlspecialchars((string)$c['app_id'])?>" placeholder="支付宝应用 APPID"><label>应用私钥</label><textarea name="app_private_key" placeholder="<?=$c['app_private_key']?'已保存；不修改请留空':'粘贴应用私钥'?>"></textarea><div class="note">私钥保存在服务器 storage/config.json，不会重新显示。</div><label>支付宝公钥</label><textarea name="alipay_public_key" placeholder="支付宝公钥"><?=htmlspecialchars((string)$c['alipay_public_key'])?></textarea><label>异步通知地址（可留空自动生成）</label><input name="notify_url" value="<?=htmlspecialchars((string)$c['notify_url'])?>" placeholder="<?=htmlspecialchars(base_url().'/notify.php')?>"><div class="note code">当前使用：<?=htmlspecialchars(notify_url($c))?></div><button class="btn">保存配置</button></form></div></div></body></html>