<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';

define('WECHAT_CONFIG_FILE', STORAGE_DIR.'/wechat.json');
function load_wechat_config():array{$d=['mch_id'=>'','app_id'=>'','api_v2_key'=>'','h5_enabled'=>false,'jsapi_enabled'=>false,'notify_url'=>''];if(!is_file(WECHAT_CONFIG_FILE))return $d;$j=json_decode((string)file_get_contents(WECHAT_CONFIG_FILE),true);return is_array($j)?array_merge($d,$j):$d;}
function save_wechat_config(array $c):void{if(file_put_contents(WECHAT_CONFIG_FILE,json_encode($c,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX)===false)throw new RuntimeException('无法写入 storage/wechat.json');@chmod(WECHAT_CONFIG_FILE,0600);}
function wechat_notify_url(array $c):string{return trim((string)($c['notify_url']??''))?:base_url().'/wechat-notify.php';}
function wechat_ready(array $c):bool{return trim((string)$c['mch_id'])!==''&&trim((string)$c['app_id'])!==''&&trim((string)$c['api_v2_key'])!=='';}
$main=load_config();$has=!empty($main['admin_password_hash']);$wc=load_wechat_config();$error='';$success='';
if(!$has){header('Location: settings.php');exit;}
if(isset($_GET['logout'])){unset($_SESSION['alipay_admin']);header('Location: wechat-settings.php');exit;}
if(empty($_SESSION['alipay_admin'])){if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['login_password'])){if(password_verify((string)$_POST['login_password'],(string)$main['admin_password_hash'])){$_SESSION['alipay_admin']=true;header('Location: wechat-settings.php');exit;}$error='管理密码错误';}if(empty($_SESSION['alipay_admin'])){?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>微信支付配置登录</title><link rel="stylesheet" href="assets/app.css"></head><body class="provider-wechat"><div class="login-wrap"><div class="login-card"><div class="login-mark">微</div><h1>微信支付配置</h1><p>使用与支付宝配置相同的管理密码进入后台。</p><?php if($error):?><div class="alert err"><?=htmlspecialchars($error)?></div><?php endif;?><form method="post"><div class="field"><label>管理密码</label><input class="input" type="password" name="login_password" required autofocus placeholder="请输入管理密码"></div><button class="btn btn-primary btn-block">进入配置</button></form></div></div></body></html><?php exit;}}
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['save'])){try{$wc['mch_id']=trim((string)($_POST['mch_id']??''));$wc['app_id']=trim((string)($_POST['app_id']??''));$key=trim((string)($_POST['api_v2_key']??''));if($key!=='')$wc['api_v2_key']=$key;$wc['h5_enabled']=isset($_POST['h5_enabled']);$wc['jsapi_enabled']=isset($_POST['jsapi_enabled']);$wc['notify_url']=trim((string)($_POST['notify_url']??''));save_wechat_config($wc);$success='微信支付配置已保存';}catch(Throwable $e){$error=$e->getMessage();}}
$host=$_SERVER['HTTP_HOST']??'localhost';
?>
<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>微信支付配置</title><link rel="stylesheet" href="assets/app.css"></head><body class="provider-wechat">
<header class="app-header"><div class="header-inner"><a class="brand" href="./"><div class="brand-mark">微</div><div><div class="brand-title">Payment Lab</div><div class="brand-sub">支付接口联调中心</div></div></a><nav class="top-nav"><a href="./">支付宝测试</a><a href="wechat.php">微信支付</a><a href="settings.php">支付宝配置</a><a class="active" href="wechat-settings.php">微信配置</a></nav></div></header>
<main class="page"><section class="hero"><div><div class="eyebrow">WECHAT PAY SETTINGS</div><h1>微信支付接口配置</h1><p>配置 Native、H5 与 JSAPI 支付所需的商户信息和回调地址。</p></div><div class="status-pill <?=wechat_ready($wc)?'':'off'?>"><?=wechat_ready($wc)?'配置完整':'配置未完成'?></div></section>
<div class="notice success"><span class="notice-dot"></span><div>Native 回调：<span class="code"><?=htmlspecialchars(wechat_notify_url($wc))?></span><br>JSAPI 授权目录：<span class="code"><?=htmlspecialchars(base_url().'/')?></span> · JS 安全域名：<span class="code"><?=htmlspecialchars(explode(':',$host)[0])?></span></div></div>
<?php if($success):?><div class="alert ok"><?=htmlspecialchars($success)?></div><?php endif;?><?php if($error):?><div class="alert err"><?=htmlspecialchars($error)?></div><?php endif;?>
<form method="post" autocomplete="off"><input type="hidden" name="save" value="1">
<section class="section-card"><div class="section-head"><div><h2>商户信息</h2><div class="card-sub">微信支付商户号与绑定应用</div></div></div><div class="section-body"><div class="form-grid">
<div class="form-label">商户号 PartnerID</div><div><input class="input" name="mch_id" value="<?=htmlspecialchars((string)$wc['mch_id'])?>" placeholder="微信支付商户号 mch_id"></div>
<div class="form-label">授权绑定 AppID</div><div><input class="input" name="app_id" value="<?=htmlspecialchars((string)$wc['app_id'])?>" placeholder="公众号/开放平台 AppID"></div>
<div class="form-label">APIv2 密钥</div><div><input class="input" type="password" name="api_v2_key" placeholder="<?=$wc['api_v2_key']?'已保存；不修改请留空':'输入 APIv2 密钥'?>"><div class="help">密钥仅保存到服务器 <span class="code">storage/wechat.json</span>，页面不会回显。</div></div>
</div></div></section>
<section class="section-card"><div class="section-head"><div><h2>支付能力</h2><div class="card-sub">按商户已开通的能力启用对应入口</div></div></div><div class="section-body" style="display:grid;gap:12px"><div class="switch-row"><div class="switch-copy"><b>H5 支付</b><div>移动浏览器唤起微信支付</div></div><label class="toggle"><input type="checkbox" name="h5_enabled" <?=$wc['h5_enabled']?'checked':''?>><span></span></label></div><div class="switch-row"><div class="switch-copy"><b>JSAPI 支付</b><div>微信内直接发起支付，需要 OAuth / openid</div></div><label class="toggle"><input type="checkbox" name="jsapi_enabled" <?=$wc['jsapi_enabled']?'checked':''?>><span></span></label></div></div></section>
<section class="section-card"><div class="section-head"><div><h2>回调设置</h2><div class="card-sub">支付成功后的服务器通知入口</div></div></div><div class="section-body"><div class="form-grid"><div class="form-label">异步通知地址</div><div><input class="input" name="notify_url" value="<?=htmlspecialchars((string)$wc['notify_url'])?>" placeholder="<?=htmlspecialchars(base_url().'/wechat-notify.php')?>"><div class="help">留空自动使用：<span class="code"><?=htmlspecialchars(wechat_notify_url($wc))?></span></div></div></div></div></section>
<div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap"><a class="btn btn-soft" href="wechat.php">返回微信测试</a><div style="display:flex;gap:10px"><a class="btn btn-soft" href="?logout=1">退出登录</a><button class="btn btn-primary" type="submit">保存微信配置</button></div></div>
</form><div class="footer-note">安全提示：API 密钥只应存放在服务器端，不要放进前端代码或公开仓库。</div></main></body></html>